# Generated by Django 5.2 on 2025-05-05 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='maps/')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_time', models.DateTimeField(auto_now_add=True)),
                ('number_of_angles', models.IntegerField()),
                ('position', models.CharField(choices=[('LEFT', 'left'), ('RIGHT', 'right')], max_length=10)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.map')),
                ('points', models.ManyToManyField(related_name='routes', to='app.point')),
                ('set_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_end', to='app.point')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.map')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_start', to='app.point')),
                ('routes', models.ManyToManyField(related_name='problems', to='app.route')),
            ],
        ),
        migrations.CreateModel(
            name='Scaling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_distance', models.FloatField()),
                ('point1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point1', to='app.point')),
                ('point2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point2', to='app.point')),
            ],
        ),
        migrations.AddField(
            model_name='map',
            name='scaling',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scaling', to='app.scaling'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_time_seconds', models.FloatField()),
                ('vote_time', models.DateTimeField(auto_now_add=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='app.route')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
