# Generated by Django 5.2 on 2025-05-11 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='scaling',
        ),
        migrations.AddField(
            model_name='scaling',
            name='map',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scaling', to='app.map'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scaling',
            name='point1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scaling_point1', to='app.point'),
        ),
        migrations.AlterField(
            model_name='scaling',
            name='point2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scaling_point2', to='app.point'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.map')),
                ('problems', models.ManyToManyField(related_name='projects', to='app.problem')),
            ],
        ),
    ]
